---
- name: Enable intranet services
  hosts: all
  gather_facts: no
  tasks:
   - name: latest version of httpd installed
     yum:
      name: httpd
      state: latest
   - name: latest version of firewalld installed
     yum:
      name: firewalld
      state: latest
   - name: test html page is installed
     copy:
      content: "Welcome to the Red Hat"
      dest: /var/www/html/index.html
   - name: firewalld enabled and running
     service:
      name: firewalld
      enabled: true
      state: started
   - name: firewalld permits http service
     firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
   - name: httpd enabled and running
     service:
      name: httpd
      enabled: true
      state: started
