---
- name: Install Package
  hosts: all
  vars:
   - packages: "{{ package.split('\n') }}"

  tasks:
  - name: Install package
    yum: name={{ item }} state=present
    with_items:
     - "{{ packages }}"
