---
- name: Ansible Variable Example Playbook
  hosts: all
  tasks:


    # display the variable data type
    - debug:
        msg: 
          - " 'Server Architechture'  is {{ ansible_architecture }} "
          - " Server Distribution Version is {{ ansible_distribution_version }} "
          - " 'Interface status' is {{ ansible_enp1s0.active }} "
          - " 'SELINUX Status' is {{ ansible_selinux.status }} "
          - " 'SELINUX Type' is {{ansible_selinux.type}} "          
          - " 'Display IPV4 addresses' {{ ansible_all_ipv4_addresses }} "
          - " 'Display LVM details' {{ansible_lvm}} "




